### ISSUE TITLE
Wrong navlink gets active class and animated scrolling

### ISSUE THREAD

**Issue by JonasJW** [thisissoon/angular-scrollspy#10]
Hi,

I have implemented angular-scrollspy and it works pretty well. However I still have one problem:

When I click a navigation link it scrolls to the correct section but it seems like it scrolls just before the start of this section so the navigation link of the previous section is highlighted/gets the `active` class.

Also there are no scroll animations. Is there a good way to have the actual scrolling animated?

Thanks and best regards!

**Comment by edoparearyee** [comment]
Hi @JonasJW currently this library does not have the functionality to scroll to an element. For scrolling functionality I would recommend using the browsers native `window.scrollTo()` with `behavior: "smooth"` option. See example [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo#Example)
