### ISSUE TITLE
WindoRef and forRoot no works

### ISSUE THREAD

**Issue by mobius127** [thisissoon/angular-scrollspy#13]
![image](https://user-images.githubusercontent.com/16031601/47215046-3b6c9500-d3a0-11e8-9c35-e12b2b186d7a.png)
WindowRef not found InViewportModule.forRoot not exists

**Comment by edoparearyee** [comment]
@mobius127 the `@thisissoon/angular-inviewport` dependancy has been updated but this module still needs to be updated.

In the meantime you can use v3 of angular-inviewport by running `npm i @thisissoon/angular-inviewport@3.0.1`

**Comment by edoparearyee** [comment]
This should now be fixed in v2.1.0
