### ISSUE TITLE
Threshold setting

### ISSUE THREAD

**Issue by moniuch** [thisissoon/angular-scrollspy#18]
Please provide _threshold_ parameter/input (on the `snScrollSpy` directive?), as if answering the question: "what is the threshold value to consider an element as active?"

In my use case I would see two types of units (for both height and width) that I would like to express the threshold:
- **vh/vw** (how much of vieport dimension does it have to occupy)
- **%** (how much of its own clientWidth/clientHeight does the element have to reveale to consider it active)

There should probably also be a parameter to specify whether the calculation should include/exclude margins/padding.

In the below scenario (we see a fixed, semi-transparent navbar above the green line)

![chrome_2019-01-09_21-03-56](https://user-images.githubusercontent.com/681956/50925283-2e68ba80-1452-11e9-94dd-d437769aaa2d.png)

the content is scrolled to the very bottom (ie. bottom of last section, Section 4), and as you see, the link for that section is still not activated. With the proposed feature, if we specified that 60% of the height is enough to consider an element active, the link would get highlighted, which would correspond with the intuitive perception.

**Comment by edoparearyee** [comment]
Closing as it's a dup of #1
