### ISSUE TITLE
Any chance of a running demo?

### ISSUE THREAD

**Issue by jegjessing** [thisissoon/angular-scrollspy#7]
Finding it a bit hard to actually "highlight" the ref that is active.
So a running demo would be nice

**Comment by edoparearyee** [comment]
Hi @jegjessing as mentioned in the [README.md](https://github.com/thisissoon/angular-scrollspy#example) a working demo can be found [here](https://github.com/thisissoon/angular-scrollspy/tree/master/src)

And you can view the demo on [StackBlitz](https://stackblitz.com/github/thisissoon/angular-scrollspy)
